## Conjunto de dados de 5.000 filmes
- https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

## Data processing

In [130]:
import pandas as pd
base_movies = pd.read_csv("tmdb_5000_movies.csv")
base_credits = pd.read_csv("tmdb_5000_credits.csv")

In [131]:
base_movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [132]:
base_movies.shape

(4803, 20)

In [133]:
base_credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [134]:
base_credits.shape

(4803, 4)

### Comparando colunas em comum

In [135]:
# Obter as colunas de cada DataFrame
columns_df1 = set(base_movies.columns)
columns_df2 = set(base_credits.columns)

# Colunas em comum
common_columns = columns_df1.intersection(columns_df2)
print("Colunas em comum:", common_columns)

Colunas em comum: {'title'}

#### Vamos unir as 2 tabelas
- Utilizaremos o "merge" que serve para unir colunas que tem alguma relação
- o "concat" é util para unir colunas sem relação alguma
- A coluna em comum é "title"

In [136]:
base = base_movies.merge(base_credits, on="title")
base.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [137]:
base.shape

(4809, 23)

In [138]:
# Analisando a linguagem dos filmes
# é uma base de filmes em inglês praticamente
base["original_language"].value_counts().head()

original_language
en    4510
fr      70
es      32
zh      27
de      27
Name: count, dtype: int64

In [139]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

### Encurtando a base

In [140]:

base = base[['movie_id','title','overview','genres','keywords','cast','crew']]

In [141]:
base.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [142]:
base.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

### Removendo os valores nulos que temos, são 3 em "overview"

In [143]:
base = base.dropna()

In [144]:
# Prontinho
base.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

### Vendo colunas em JSON

In [145]:
# Função para verificar se uma string é JSON válida
import json

def is_json(text):
    try:
        json.loads(text)
        return True
    except (ValueError, TypeError):
        return False

# Função para verificar se uma coluna contém JSON válido
def check_columns_for_json(df):
    for column in df.columns:
        # Verifica se pelo menos um valor na coluna é JSON válido
        is_column_json = df[column].apply(is_json).any()
        print(f"{column}: {is_column_json}")

In [146]:
# Chame a função para verificar as colunas do DataFrame
check_columns_for_json(base)

movie_id: False
title: True
overview: False
genres: True
keywords: True
cast: True
crew: True

### Filtrando a coluna genres e keywords
- Vamos pegar apenas o "name" das colunas
- Como a coluna "genre" e "keywords" estão em formato JSON temos que tratar ela

In [147]:
import json
def convert(text):
    lista = []
    for item in json.loads(text):
        lista.append(item['name'])
    return lista

In [148]:
base[["genres"]].head(2)

                                              genres
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...

In [149]:
base["genres"] = base["genres"].apply(convert)

In [150]:
# Agora temos só o nome nesta coluna
base[["genres"]].head(2)

                                          genres
0  [Action, Adventure, Fantasy, Science Fiction]
1                   [Adventure, Fantasy, Action]

In [151]:
# Agora a outra coluna
base[["keywords"]].head(2)

                                            keywords
0  [{"id": 1463, "name": "culture clash"}, {"id":...
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...

In [152]:
base["keywords"] = base["keywords"].apply(convert)

In [153]:
base[["keywords"]].head(2)

                                            keywords
0  [culture clash, future, space war, space colon...
1  [ocean, drug abuse, exotic island, east india ...

#### Para a coluna "cast" 
- Quero apenas os 3 primeiros nomes
- Vou ter que alterar a função

In [154]:
import json
def convert(text):
    lista = []
    counter = 0
    for item in json.loads(text):
        if(counter <= 3):
            lista.append(item['name'])
        else:
            break
    return lista

In [155]:
# apesar de não estar aparecendo no head por serem muitas imformações, tem a chave "name"
base[["cast"]].head(2)

                                                cast
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...

In [156]:
base["cast"] = base["cast"].apply(convert)

In [157]:
# Pegamos os 3 primeiros nomes do elenco
base[["cast"]].head(2)

                                                cast
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...

### Para a coluna "crew" queremos pegar o nome do diretor para colocar em outra coluna
- Filtraremos aonde o trabalho seja diretor e pegaremos o nome
- Desta vez criaremos uma nova coluna e não substituiremos

In [158]:
import json
def convert(text):
    lista = []
    counter = 0
    for item in json.loads(text):
        if(item["job"] == "Director"):
            lista.append(item['name'])
    return lista

In [159]:
base[["crew"]].head(2)

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [160]:
base["director"] = base["crew"].apply(convert)

In [161]:
base[["director"]].head(3)

           director
0   [James Cameron]
1  [Gore Verbinski]
2      [Sam Mendes]

#### Vamos eliminar a coluna antiga "crew"

In [162]:
base = base.drop("crew", axis=1)

In [163]:
base.head(1)

,movie_id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

### Vamos trabalhar na coluna "overview"
- Uma coluna de descrição, um texto
- Temos que dividir ela em um array para poder trabalhar melhor
- Vamos usar o "Split" do python, ela vai separar as palavras aonde tem um espaço para o inicio de outra palavra

In [164]:
base[["overview"]].head(3)

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...

In [165]:
# veja
base["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [166]:
# Ajustando a coluna
base["overview"] = base["overview"].apply(lambda x: x.split())

In [167]:
# Separados
base[["overview"]].head(3)

                                            overview
0  [In, the, 22nd, century,, a, paraplegic, Marin...
1  [Captain, Barbossa,, long, believed, to, be, d...
2  [A, cryptic, message, from, Bond’s, past, send...

### Vamos retirar de todas as colunas o espaço que tem em casos aonde tem mais de uma palavra 
- Param melhorar o aprendizado de maquina
- Exemplo: JonasRuan -> JonasRuan

In [168]:
base.head()

,movie_id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [169]:
base["genres"] = base["genres"].apply(lambda x:[i.replace(" ", "") for i in x])
base["keywords"] = base["keywords"].apply(lambda x:[i.replace(" ", "") for i in x])
base["cast"] = base["cast"].apply(lambda x:[i.replace(" ", "") for i in x])
base["director"] = base["director"].apply(lambda x:[i.replace(" ", "") for i in x])

In [170]:
# o title a gente pode deixar normal
base.head()

,movie_id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

#### Adicionando uma coluna com os valores das outras que criamos
- Coluna "tags"

In [171]:
base["tags"] = base["overview"] + base["genres"] + base["keywords"] + base["cast"] + base["director"]

In [172]:
base.head(2)

,movie_id,title,overview,genres,keywords,cast,director,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

### Criando o data frame filtrado

In [173]:
base = base[["movie_id", "title", "tags"]]

In [174]:
base.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

#### Vamos tirar de dentro da lista os valores das "tags" e deixar tudo em lower case

In [175]:
base["tags"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'MichelleRodriguez',
 'GiovanniRibisi',
 'JoelDavidMoore',
 'CCHPounder',
 'WesStudi',
 'LazAlonso',
 'DileepRao',
 'MattGerald',
 'SeanAnthonyMoran',
 'JasonWhyte',
 'ScottLawrence',
 'KellyKilgour',
 'JamesPatrickPitt',
 'SeanPatrickMurphy',
 'PeterDillon',
 'KevinDorman',
 'KelsonHenderson',
 'DavidVanHorn',
 'JacobTomuri',
 'MichaelBlain-Rozgay',
 'JonCurry',
 'LukeHawker',
 'WoodySchultz',
 'PeterMensah',
 'SoniaYee',
 'JahnelCurfman',
 'IlramChoi',
 'KylaWarren',
 'LisaRoumain',
 'DebraWilson',
 'ChrisMala',
 'TaylorKibby',
 'JodieLandau',
 'JulieLamm',
 'CullenB.Madden',
 'JosephBradyMadden',
 'FrankieTorres',
 'AustinWilson',
 'SaraWilson',
 'TamicaWashington-Miller',
 'LucyBriant',
 'NathanMeister',
 'GerryBlair',
 'MatthewChamberlain',
 'PaulYates',
 'WrayWilson',
 'JamesGaylyn',
 'MelvinLenoClarkIII',
 'CarvonFutrell',
 'BrandonJelkes',
 'MicahMoch',
 'HanniyahMuhammad',
 'ChristopherNolen',
 'ChristaOliver',
 'AprilMarieThomas',
 'BravitaA.Threatt',
 'ColinBleasdale',
 'MikeBodnar',
 'MattClayton',
 'NicoleDionne',
 'JamieHarrison',
 'AllanHenry',
 'AnthonyIngruber',
 'AshleyJeffery',
 'DeanKnowsley',
 'JosephMika-Hunt',
 'TerryNotary',
 'KaiPantano',
 'LoganPithyou',
 'StuartPollock',
 'Raja',
 'GarethRuck',
 'RhianSheehan',
 'T.J.Storm',
 'JodieTaylor',
 'AliciaVela-Bailey',
 'RichardWhiteside',
 'NikieZambo',
 'JuleneRenee',
 'JamesCameron']

In [176]:
base['tags'] = base['tags'].apply(lambda x: " ".join(x))

In [177]:
base["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [178]:
# Colocando em lower case tudo para melhorar o ML
base['tags'] = base['tags'].apply(lambda x: x.lower())

In [179]:
# Tudo perfeito agora
base["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

### Vamos usar a lib "nltk" tecnicas de linguagem natural (NLP
- https://www.nltk.org/
- Serve para simplificar as palavras parecidas para melhorar o machine learn
- Existem várias mas aqui vamos utilizar o "PorterStemmer" desta lib é uma ferramenta popular de stemming que reduz palavras à sua raiz básica ou "stem". Isso é útil em muitas tarefas de processamento de linguagem natural, como análise de texto e recuperação de informações, onde a variação das palavras deve ser tratada de forma unificada.

In [180]:
import nltk
from nltk.stem import PorterStemmer
# Inicializar o stemmer
stemmer = PorterStemmer()

In [181]:
# Exemplo do que o steammer faz, todas as palavras viraram "love"
arr = ["loved", "lovely", "loving", "love"]
for i in arr:
    print(stemmer.stem(i))

love
love
love
love

In [182]:
# Função para usar no database
def fun_stemmer(text):
    list = []
    for i in text.split(): # precisa do split para não pegar cada letra da palavra
        list.append(stemmer.stem(i))
    return " ".join(list) # join serve para retornar a frase junta e não separadas em um array

In [183]:
base['tags'] = base['tags'].apply(fun_stemmer)

In [184]:
base["tags"][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [185]:
# 4806 linhas
base["tags"].shape

(4806,)

### Vectorization
- A transformação de dados em vetores numéricos para que modelos possam ser treinados ou fazer previsões. Um exemplo comum é a vetorização de texto usando "CountVectorizer" do scikit-learn.
- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer

In [186]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
                            stop_words = "english", # Padrão "none". Remove palavras comuns que geralmente não são informativas.
                            max_features = 5000 # Padrão "none".Fica em 5mil colunas no maximo a matriz, Mantém apenas os max_features termos mais frequentes.
                            )

In [187]:
# Ajustando o vetor de contagem aos textos
texts = base["tags"]
X_vec = vectorizer.fit_transform(texts)

In [188]:
X_vec.shape

(4806, 5000)

In [189]:
# Mostrando os recursos (features) extraídos
print(vectorizer.get_feature_names_out())

['000' '007' '10' ... 'zoo' 'zooeydeschanel' 'zoëkravitz']

In [190]:
# 5 mil igual definimos no "max_features"
len(vectorizer.get_feature_names_out())

5000

In [191]:
# Mostrando a matriz de contagem
print(X_vec.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [192]:
# IMPORTANTE, passando para o array para ficar mais fácil de usar
X_vec = X_vec.toarray()

### Usaremos o "cosine_similarity" para recomendar os filmes semelhantes
- https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html#sklearn.metrics.pairwise.cosine_similarity
- A similaridade do cosseno (cosine similarity) é uma medida usada para determinar o quão similares são dois vetores, independentemente de sua magnitude. No contexto de aprendizado de máquina e processamento de linguagem natural (NLP), essa métrica é frequentemente utilizada para comparar documentos, frases ou qualquer tipo de texto representado como vetores.

In [193]:
from sklearn.metrics.pairwise import cosine_similarity

In [194]:
# Calcula as similaridades de todas as linhas entre elas mesmas da coluna que escolhemos, no caso a "tags"
similarity = cosine_similarity(X_vec)

In [195]:
# Isso que vamos usar para comparar com os próprios filmes
similarity

array([[1.        , 0.06666667, 0.07559289, ..., 0.0421637 , 0.        ,
        0.        ],
       [0.06666667, 1.        , 0.07559289, ..., 0.02108185, 0.        ,
        0.02222222],
       [0.07559289, 0.07559289, 1.        , ..., 0.02390457, 0.        ,
        0.        ],
       ...,
       [0.0421637 , 0.02108185, 0.02390457, ..., 1.        , 0.04264014,
        0.0421637 ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 1.        ,
        0.08989331],
       [0.        , 0.02222222, 0.        , ..., 0.0421637 , 0.08989331,
        1.        ]])

In [196]:
# Vendo só que ele deixa igual quando faz o calculo
similarity.shape

(4806, 4806)

### Explicando a função abaixo

In [197]:
base[base["title"] == "Batman"] # por isso pegamos o indice

      movie_id   title                                               tags
1360       268  Batman  the dark knight of gotham citi begin hi war on...
1361      2661  Batman  the dark knight of gotham citi begin hi war on...
4272       268  Batman  the dynam duo face four super-villain who plan...
4273      2661  Batman  the dynam duo face four super-villain who plan...

In [198]:
base[base["title"] == "Batman"].index[0]

1360

In [199]:
base.head(2)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."

In [285]:
def recommend(movie):
    movie_index = base[base["title"] == movie].index[0] # temos que pegar o valor do primeiro indice valor(index[0]) pois tem filmes que tem titulos iguais dai ia gerar recomendações do mesmo filme só que em outras linguas talvez
    similarity_movie = similarity[movie_index] # pegamos a similaridade do filme escolhido pelo indice, ele calcula a similaridade dele a respeito de toda base que já escolhemos antes pelo coseno -> "cosine_similarity(X_vec)"
    
    
    movies_list_index = sorted(list(enumerate(similarity_movie)),reverse = True, key = lambda x: x[1])[1:6] # vai puxar a similaridade de toda a lista´, pegamos do indice 1 até 6 pois o 0 é ele mesmo então não faria sentido.
    # o "reverse = true" do sorted vai pegar da ordem do maior para o menor
    # e a "key = lambda x: x[1]" serve para informar que queremos o segundo valor para escolher como ordernar no caso o primeiro valor é o indice "0" o segundo é a similaridade que é o "1"

    
    for i in movies_list_index:  # printando os valores
        print(base.iloc[i[0]].title) # passando "i[0]" pois assim vem só o indice do filme sem a % de similaridade
        #  A função "iloc" retorna a linha baseada no número do indice

In [286]:
recommend("Avatar")

Aliens vs Predator: Requiem
Predator
Battle: Los Angeles
Falcon Rising
Independence Day

In [287]:
recommend("Batman")

Batman
Batman & Robin
Batman
Batman Returns
The R.M.

## Exportando o modelo treinado e o database alterado
- precisamos fazer isso pois vou criar um site pelo vscode

In [289]:
import joblib
# # Exportando a matriz de similaridade usando joblib
# joblib.dump(similarity, 'similarity_movies.pkl')

['similarity_movies.pkl']

In [290]:
# Exportando o database
# Salve o DataFrame como CSV
#base.to_csv('movies_pronto.csv', index=False)